export const SELECT_VIDEO_REQUEST = "VIDEO_REQUEST"
export const SELECT_VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const SELECT_VIDEO_FAIL = "VIDEO_FAIL"
export const SELECT_CLEAR_ERRORS = "CLEAR_ERRORS"

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL"

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL"

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL"

export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST"
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL"
