export const SELECT_VIDEO_REQUEST = "VIDEO_REQUEST"
export const SELECT_VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const SELECT_VIDEO_FAIL = "VIDEO_FAIL"
export const SELECT_CLEAR_ERRORS = "CLEAR_ERRORS"
